### ISSUE TITLE
Can you add a CompletedCall method?

### ISSUE THREAD

**Issue by AlfredCCandorTechnology** [Aarondorn2/CallableMessaging#1]
Similar concept as ReachedMaxCalls method:
https://github.com/Aarondorn2/CallableMessaging/blob/b5898fb053e3931f69f430ad8bbe3f3fc02a5edd/CallableMessaging/ICallable.cs#L88

Add a method to `IRepeatedCallable` that is called when the limit set by `MaxCalls` is not reached and `ShouldContinueCalling` is set to false. A method like `CompletedCall()` in reference to `ICallable.CallAsync()` completing. The use case is to kick off the next step in a process chain like when the repeatable code is complete and now it is time to send emails with the results. The emailing code isn't a repeatable piece of the process while polling for the results that the email is based on is a repeatable process.

**Comment by Aarondorn2** [comment]
Absolutely! Do you want to submit a PR and I'll merge/update nuget?

**Comment by Aarondorn2** [comment]
A suggestion, we should rename/repurpose "ReachedMaxCalls" and pass in a book "reachedMaxCalls".
``` 
public Task CompletedCall(bool reachedMaxCalls)
```

**Comment by AlfredCCandorTechnology** [comment]
Sure, is this done by giving me permissions to push branches to this repo or some other way?

**Comment by Aarondorn2** [comment]
Implemented with #2
