### ISSUE TITLE
Suggestion: Add max calls property to IConcurrentCallable and IRateLimitCallable

### ISSUE THREAD

**Issue by AlfredCCandorTechnology** [Aarondorn2/CallableMessaging#4]
As is found in `IRepeatedCallable`, add a property to limit the number of attempts to retry an `IConcurrentCallable` and `IRateLimitCallable` before the message is discarded. The intent it to prevent a comedy of issues all coming together to create a long running chain of repeated queued messages.

Also, the `Consumer.Consume()` method doesn't have a way to preserve message attributes added by outside code. When `.Publish()` is called on a `IConcurrentCurrent` message during a requeue that is caused due to a lock, any desired message attributes from the original message are lost.

**Comment by Aarondorn2** [comment]
After reviewing the root cause, we discussed adding support for message metadata (message Attributes for AWS SQS) instead of another counter on the message types themselves
